# Generated by Django 4.0.4 on 2022-05-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozinha', '0004_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('1', 'comidas'), ('2', 'bebidas'), ('3', 'sobremesas')], default=1, max_length=2, verbose_name='Tipo do produto'),
        ),
    ]
